### ISSUE TITLE
Support for Xbox Controller

### ISSUE THREAD

**Issue by OsoaGitHub** [wwwwwwzx/NXController#3]
Hi, first off I want to thank you for your program, but I think a great enhancement would be adding support for Xbox Controller. This, paired with WiinUSoft, would mean that Wii U Pro Controller, and other controller, support would be possible. I have tried to accomplish this with AntiMicro, but I have run into some problems, such as a drifting Pro Controller, which is not good. I hope you consider my request!

**Comment by ciberharry97** [comment]
This would be awesome, and also adding multiple controllers
